### PR TITLE
update app structure, create ContainerVC

### PR DESCRIPTION
**Pull request by vmsavka**
Anybody, Please review it and leave comments.

### CODE REVIEW

**Comment by vmsavka** [comment]
updated pull request

**Comment by vmsavka** [comment]
new commit

**Comment by mark-flixwagon** [comment]
@vmsavka The latest branch does not compile for me, can you fix this please?

**Comment by vmsavka** [comment]
please switch to the NewsFeed branch and leave your feedback there, it is a fork from current branch

**Pull request merged**
